version: '3'

services:
   db:
     image: hinterlands/mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpressroot
       MYSQL_DATABASE: wordpressdb
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: hinterlands/wordpress
     ports:
       - "8000:80"
     volumes:
       - ./src/plugins:/usr/html/wp-content/plugins
       - ./src/themes:/usr/html/wp-content/themes
     restart: always
     environment:
       DB_HOST: db:3306
       DB_NAME: wordpressdb
       DB_USER: wordpress
       DB_PASS: wordpress
       DOMAIN: woo.hinterlands.tech
       EMAIL: dev@hinterlands.tech
volumes:
    db_data:
