version: '3'

services:
   db:
     image: hinterlands/mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file:
       - env/mariadb.env

   wordpress:
     depends_on:
       - db
     image: hinterlands/wordpress
     ports:
       - "8000:80"
     volumes:
       - app_data:/usr/html
       - ./src/plugins:/usr/html/wp-content/plugins
       - ./src/themes:/usr/html/wp-content/themes
     restart: always
     env_file:
       - env/wordpress.env
     environment:
       - LOCAL_DEV=0

volumes:
    app_data:
    db_data:
