version: '3'

services:
   db:
     image: hinterlands/mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: vanillaroot
       MYSQL_DATABASE: vanilladb
       MYSQL_USER: vanilla
       MYSQL_PASSWORD: vanilla

   vanilla:
     depends_on:
       - db
     image: hinterlands/vanilla
     ports:
       - "9000:80"
     volumes:
       - ./src/plugins:/usr/html/plugins
       - ./src/themes:/usr/html/themes
     restart: always
     environment:
       DB_HOST: db:3306
       DB_NAME: vanilladb
       DB_USER: vanilla
       DB_PASS: vanilla
       VNL_VERSION: 2.5.1
volumes:
    db_data:
