version: '3'

services:
   db:
     image: hinterlands/mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     env_file:
       - env/mariadb.env

   vanilla:
     depends_on:
       - db
     image: hinterlands/vanilla
     ports:
       - "8000:80"
     volumes:
       - app_data:/usr/html
       - ./src/plugins:/usr/html/plugins
       - ./src/themes:/usr/html/themes
     restart: always
     env_file:
       - env/vanilla.env

volumes:
    app_data:
    db_data:
